# Generated by Django 3.2.8 on 2021-12-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_shopuser_avatar_url'),
        ('authapp', '0009_update_user_profile'),
    ]

    operations = [
    ]
